services:
  ingestor-db:
    container_name: ingestor-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - shared-network

  ingestor-frontend:
    container_name: ingestor-frontend
    build: ./frontend
    ports:
      - "8084:8501"
    environment:
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - shared-network

volumes:
  ingestor-db:

networks:
  shared-network:
    external: true